# Ficheiro de Blueprint do Render (Infraestrutura como Código)
# https://render.com/docs/blueprint-spec

services:
  # Define o nosso serviço
  - name: ubuntu-tailscale-agent
    type: worker
    region: virginia
    plan: free
    runtime: docker
    # Aponta para o repositório Git onde estes ficheiros estão.
    # O Render preencherá isto automaticamente se o ficheiro estiver no repositório.
    repo: https://github.com/ReivsonAicury/AgenteTailscaleRender # <-- ALTERE ISTO!
    # Especifica a ramificação a ser usada
    branch: main
    # Define as variáveis de ambiente necessárias
    envVars:
      - key: TAILSCALE_AUTHKEY
        # Use 'sync: false' para indicar que é uma variável secreta
        # que deve ser definida no painel do Render
        sync: false
